version: '3.8'

services:
  neo4j:
    image: neo4j:5 # Use a recent Neo4j version (e.g., 5.x)
    container_name: traderag_neo4j
    ports:
      - "7474:7474" # Neo4j Browser / HTTP API
      - "7687:7687" # Bolt driver port
    volumes:
      - neo4j_data:/data # Persist data outside the container
    environment:
      # Set authentication details explicitly
      # NEO4J_AUTH is the primary mechanism for initialization/reset
      - NEO4J_AUTH=neo4j/changeme123
      # Recommended settings for performance/heap size (adjust as needed based on system RAM)
      # - NEO4J_server_memory_heap_initial__size=512m
      # - NEO4J_server_memory_heap_max__size=2G
    restart: unless-stopped

volumes:
  neo4j_data: # Define the named volume

# Add other services here later (e.g., FastAPI backend) 